import Image from "next/image";
import Link from "next/link";
import { manufacturingLanguage as lang } from "@/lib/manufacturing-site";

export function CompanyAbout({ team }: { team: { name: string; initials: string; role: string; copy: string; photo?: string }[] }) {
  const tr = lang === "tr";
  return <main className="page-shell">
    <section className="grid items-center gap-8 lg:grid-cols-2"><div><p className="eyebrow">{tr ? "ARDIÇ hakkında" : "About ARDIÇ"}</p><h1 className="mt-4 font-display text-4xl leading-tight md:text-6xl">{tr ? "Tasarımın arkasında bir üretim ekibi." : "A fabrication team behind your design."}</h1><p className="mt-5 text-lg leading-8 text-ink/75">{tr ? "ARDIÇ Design & Fabrication, İstanbul merkezli bir EPSLAM şirketidir. Aile üretim deneyimini mimari düşünce, iç mekân tasarımı, dijital üretim ve el işçiliğiyle birleştiriyoruz." : "ARDIÇ Design & Fabrication is an Istanbul-based EPSLAM company. We bring family production experience together with architectural thinking, interior design, digital fabrication and craft."}</p><p className="mt-4 leading-8 text-ink/70">{tr ? "Sabit ve hareketli mobilya, cephe elemanları ve özel üretim projelerinde tasarım geliştirme, imalat ve montajın birlikte çalışmasını sağlıyoruz." : "For fitted and freestanding furniture, facade elements and custom objects, we coordinate design development, fabrication and installation."}</p><Link href="/fabrication" className="text-link mt-6 inline-block">{tr ? "Atölyeyi ve üretim sürecini görün" : "See the workshop and production process"} →</Link></div><div className="relative aspect-[4/3] bg-smoke/30"><Image src="/projects/portfolio/cnc-manufacturing-processes/cnc-manufacturing-processes-01.jpeg" alt={tr ? "ARDIÇ atölyesinde büyük form üretimi" : "Large form fabrication in the ARDIÇ workshop"} fill priority sizes="(min-width: 1024px) 48vw, 100vw" className="object-cover" /></div></section>
    <section className="mt-14 border-t border-ink/15 pt-10"><p className="eyebrow">{tr ? "Projenin arkasındaki insanlar" : "The people behind the project"}</p><h2 className="mt-3 font-display text-3xl md:text-4xl">{tr ? "Ekibimiz" : "Our team"}</h2><div className="mt-7 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{team.map(person => <article key={person.name} className="border-t border-ink/15 pt-5"><div className="flex items-center gap-4">{person.photo ? <Image src={person.photo} alt={person.name} width={64} height={64} className="h-16 w-16 object-cover" /> : <span aria-hidden="true" className="flex h-16 w-16 shrink-0 items-center justify-center bg-smoke/40 font-display text-2xl text-bronze">{person.initials}</span>}<div><h3 className="font-display text-2xl">{person.name}</h3><p className="mt-1 text-sm leading-5 text-bronze">{person.role}</p></div></div><p className="mt-4 leading-7 text-ink/70">{person.copy}</p></article>)}</div></section>
    <section className="mt-12 flex flex-wrap items-center justify-between gap-6 border-t border-ink/15 pt-8"><p className="max-w-xl text-lg leading-8">{tr ? "Projenizin ölçüsünü, kullanımını ve hedeflediğiniz sonucu birlikte değerlendirelim." : "Let's review the dimensions, use and intended result of your project."}</p><Link href="/contact#brief" className="button-primary">{tr ? "Projenizi paylaşın" : "Share your project"} →</Link></section>
  </main>;
}
